### ISSUE TITLE
使用此模块导致NFC功能无法使用

### ISSUE THREAD

**Issue by 1335344215** [symbuzzer/systemless-hosts-KernelSU-module#5]
![Screenshot_2023-09-28-22-38-26-740_com android settings](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/33363399/6f6ccba8-2c77-4944-8f40-f54e787ad130)
![Screenshot_2023-09-28-22-38-15-815_com android settings](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/33363399/214e894f-dacf-4828-ba71-9797532a445d)
![Screenshot_2023-09-28-22-16-39-935_me weishu kernelsu](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/33363399/f37a22e2-5936-4f33-9f79-816d42ade7b2)

以下是小米的日志估计不全，手机型号红米note11tPro

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/nfc/NfcService$NxpNfcAdapterService;
	at com.android.nfc.NfcService.<init>(NfcService.java:1091)
	at com.android.nfc.NfcApplication.onCreate(NfcApplication.java:107)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6992)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.ClassNotFoundException: com.android.nfc.NfcService$NxpNfcAdapterService
	... 13 more

**Comment by symbuzzer** [comment]
@1335344215 该错误是由模块引起的。 关闭模块后是否仍然遇到同样的问题？ 您到底遇到了什么错误？

**Comment by 1335344215** [comment]
目前我已经尝试过一个个关闭模块然后重启看看有没有恢复NFC功能，当关闭到此模块后然后重启手机后NFC功能呢恢复正常，接着我把其他已经关闭的模块全部打开（注：本模块未启用的状态）然后重启手机NFC功能正常，然后我接着把本模块启用后重启手机后NFC功能无法使用

**Comment by 1335344215** [comment]
![Screenshot_2023-09-28-21-07-26-668_com miui tsmclient](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/33363399/e07c12a4-cf0c-4fab-aafb-374bb2e7966c)
![Screenshot_2023-09-28-21-05-32-687_com android settings](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/assets/33363399/17df35bb-3a0a-4137-85d3-47e67cb5a486)

**Comment by symbuzzer** [comment]
@1335344215 您是唯一报告此问题的人。 有机会在其他设备上尝试一下吗？

**Comment by 1335344215** [comment]
我目前手上暂无其他支持kerner su的设备,但是我使用magical Overlayfs模块却不会造成类似的问题

**Comment by Gleb2372372** [comment]
Same problem on Redmi note 12 pro 5g HyperOS 1.0.8.0
